const data = [
    {
      id: 1,
      name: "Invicta Men's Pro Diver",
      img: "./images/watch1.jpg",
      price: 74,
      cat: "Dress",
    },
    {
      id: 11,
      name: "Invicta Men's Pro Diver 2",
      img: "./images/watch2.jpg",
      price: 74,
      cat: "Dress",
    },
    {
      id: 2,
      name: "Timex Men's Expedition Scout ",
      img: "./images/watch3.jpg",
      price: 40,
      cat: "Sport",
    },
    {
      id: 3,
      name: "Breitling Superocean Heritage",
      img: "./images/watch4.jpg",
      price: 200,
      cat: "Luxury",
    },
    {
      id: 4,
      name: "Casio Classic Resin Strap ",
      img: "./images/watch5.jpg",
      price: 16,
      cat: "Sport",
    },
    {
      id: 5,
      name: "Garmin Venu Smartwatch ",
      img: "./images/watch6.jpg",
      price: 74,
      cat: "Casual",
    },
    {
      id: 6,
      name: "Invicta Men's Pro Diver",
      img: "./images/watch7.jpg",
      price: 74,
      cat: "Dress",
    },
    {
      id: 7,
      name: "Invicta Men's Pro Diver 2",
      img: "./images/watch8.jpg",
      price: 74,
      cat: "Dress",
    },
    {
      id: 8,
      name: "Timex Men's Expedition Scout ",
      img: "./images/watch9.jpg",
      price: 40,
      cat: "Sport",
    },
    {
      id: 9,
      name: "Breitling Superocean Heritage",
      img: "./images/watch10.jpg",
      price: 200,
      cat: "Luxury",
    },
    {
      id: 10,
      name: "Casio Classic Resin Strap ",
      img: "./images/watch11.jpg",
      price: 16,
      cat: "Sport",
    },
    {
      id: 14,
      name: "Garmin Venu Smartwatch ",
      img: "./images/watch12.jpg",
      price: 74,
      cat: "Casual",
    },
    {
      id: 12,
      name: "Casio Classic Resin Strap ",
      img: "./images/watch13.jpg",
      price: 16,
      cat: "Sport",
    },
    {
      id: 13,
      name: "Garmin Venu Smartwatch ",
      img: "./images/watch14.jpg",
      price: 74,
      cat: "Casual",
    },
  ];